# This file was generated by GoReleaser. DO NOT EDIT.
class Lcg < Formula
  desc "LaunchDarkly Code Generator to build custom flag wrappers"
  homepage "https://launchdarkly.com"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/launchdarkly-labs/lcg/releases/download/v0.1.3/lcg_0.1.3_Darwin_x86_64.tar.gz"
    sha256 "1d961bd99ecae5db5fa7266e900de2ae45eab857d33ca4228b783105a8ad874d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly-labs/lcg/releases/download/v0.1.3/lcg_0.1.3_Linux_x86_64.tar.gz"
      sha256 "510b85d45a2f6be33173174acfe343b61fff243439e51c069f674eeaaa161306"
    end
  end

  def install
    bin.install "lcg"
  end
end
