# This file was generated by GoReleaser. DO NOT EDIT.
class Lcg < Formula
  desc "LaunchDarkly Code Generator to build custom flag wrappers"
  homepage "https://launchdarkly.com"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/launchdarkly-labs/lcg/releases/download/v0.1.2/lcg-private_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "49c22feedcd63687fc35fd4923fa329e4e69f84a508c8a379360b9c9248f1927"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly-labs/lcg/releases/download/v0.1.2/lcg-private_0.1.2_Linux_x86_64.tar.gz"
      sha256 "ad670958a68c47a636a42b8d9ef05b93829b411aa3f1ddfe3ea8ea580d7862fb"
    end
  end

  def install
    bin.install "lcg"
  end
end
